### ISSUE TITLE
Build fails while using with react-color component

### ISSUE THREAD

**Issue by bcinarli** [casesandberg/reactcss#142]
react-color depends on 1.2.2 version, and when it is installed, during the build I get following error;

```
ERROR in ./~/reactcss/lib/index.js
Module build failed: Error: Plugin 0 specified in "/project-path/node_modules/reactcss/.babelrc" provided an invalid property of "__wrapped__"

 @ ./~/react-color/lib/components/alpha/Alpha.js 22:16-35
 @ ./~/react-color/lib/index.js
```

when I separately install 1.2.0 version, everything works fine.

**Comment by casesandberg** [comment]
Look like webpack might have an issue finding a plugin? (Issue Thread here: https://github.com/lodash/babel-plugin-lodash/issues/83). The only plugn that is there, and it was added recently, is the lodash plugin: https://github.com/casesandberg/reactcss/blob/master/.babelrc#L8. I am investigating.

**Comment by casesandberg** [comment]
That is weird. It seems not to be an issue on this end as far as I can tell. There wasn't any changes that would affect something like this from 1.2.0 to 1.2.2. Can you clear your node_modules, reinstall and let me know if this is still an issue?

**Comment by gufranmirza** [comment]
"plugins": [ "babel-plugin-lodash"]

if your main webpack config is missing above plugin it wont work, after adding it works fine.

**Comment by PDS42** [comment]
I'm still experiencing this issue, with the following logs:

```ERROR in ./node_modules/reactcss/lib/index.js
toolbox             | Module build failed: Error: Plugin 0 specified in "/app/node_modules/reactcss/.babelrc" provided an invalid property of "__wrapped__"
toolbox             |     at Plugin.init (/app/node_modules/babel-core/lib/transformation/plugin.js:131:13)
toolbox             |     at Function.normalisePlugin (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
toolbox             |     at /app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
toolbox             |     at Array.map (native)
toolbox             |     at Function.normalisePlugins (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
toolbox             |     at OptionManager.mergeOptions (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
toolbox             |     at OptionManager.init (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
toolbox             |     at File.initOptions (/app/node_modules/babel-core/lib/transformation/file/index.js:212:65)
toolbox             |     at new File (/app/node_modules/babel-core/lib/transformation/file/index.js:135:24)
toolbox             |     at Pipeline.transform (/app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)```

I've tried the solutions I found here and there, none worked. I would appreciate any help on this issue!

**Comment by casesandberg** [comment]
I removed the `.babelrc` from the NPM payload and it fixes this issue!
